#!/usr/bin/env bash

# Run docker container if it's not up yet
if ! [[ $(docker ps | grep shlink_api_spec_ui) ]]; then
    docker compose up -d
fi

docker exec -it shlink_api_spec_ui /bin/sh -c "cd /shlink-api-spec && $*"
